#!/bin/bash
#3panes layout - 1 bottom - 2 up


#---------------------------------
#|              |                |
#|              |                |
#|              |                |
#|      1       |       2        |
#|              |                |
#|              |                |
#|-------------------------------|
#|                               |
#|                               |
#|              3                |
#|                               |
#|                               |
#|                               |
#--------------------------------


    SN="Layout_2pane"
    tmux has-session -t $SN &>/dev/null
    if [ $? != 0 ]
    then
        tmux new -s $SN -n conf -d
        tmux new-window -t $SN:2 -n misc
        tmux select-window -t $SN:1
        tmux send-keys "aspell" C-m
        tmux split-window -v -p 50 
	tmux send-keys "links2 http://www.google.ca" C-m
        tmux select-pane -t 0
	tmux split-window -h -p 50
	tmux send-keys "wordgrinder" C-M
        fi
        tmux -2 attach -t $SN

