#!/bin/bash
#3panes Layout - Horizontal split on left.

#---------------------------------
#|               |               |
#|               |               |
#|               |               |
#|      1        |               |
#|               |               |
#|               |               |
#|---------------|        3      |
#|               |               |
#|               |               |
#|      2        |               |
#|               |               |
#|               |               |
#|               |               |
#---------------------------------

    SN="Layout"
    tmux has-session -t $SN &>/dev/null
    if [ $? != 0 ]
    then
        tmux new -s $SN -n conf -d
        tmux new-window -t $SN:2 -n misc
        tmux select-window -t $SN:1
        tmux send-keys "cat one.txt" C-m
        tmux split-window -h -p 50 # split vertically by 50%
        tmux send-keys "cat two.txt" C-m
        tmux select-pane -t 0
	tmux split-window -v -p 50
	tmux send-keys "cat three.txt" C-m
        fi
        tmux -2 attach -t $SN

